### ISSUE TITLE
Writing of large GSD files fails

### ISSUE THREAD

**Issue by InnocentBug** [glotzerlab/gsd#48]
## Description

Writing a GSD file with 2^28 particles crashes GSD consistently in the writing process.

## Script

```python
import sys
import gsd
import gsd.hoomd
import numpy as np

def main(argv):
    if len(argv) != 1:
        print("Usage: ./test.py")
        return
    test(2**26)
    print("2^26 passed")
    test(2**27)
    print("2^27 passed")
    test(2**28)
    print("2^28 passed")

def test(size):

    s = gsd.hoomd.Snapshot()
    s.particles.N = int(size)
    s.particles.position = np.zeros( (s.particles.N,3) )
    s.particles.position += 0.5
    s.particles.velocity = np.zeros( (s.particles.N,3) )
    s.particles.velocity += 0.3
    s.particles.image = np.zeros( (s.particles.N,3), dtype=np.int )
    s.particles.mass = np.ones(s.particles.N)


    with gsd.hoomd.open(name="temp.gsd",mode="wb") as f:
        f.append(s)

if __name__ == "__main__":
    main(sys.argv)

```

## Output
2^26 passed
2^27 passed
Traceback (most recent call last):
  File "test.py", line 36, in <module>
    main(sys.argv)
  File "test.py", line 17, in main
    test(2**28)
  File "test.py", line 33, in test
    f.append(s)
  File "/usr/local/lib/python3.5/dist-packages/gsd/hoomd.py", line 567, in append
    self.file.write_chunk(path + '/' + name, data)
  File "fl.pyx", line 519, in gsd.fl.GSDFile.write_chunk
OSError: [Errno 0] Success: 'particles/position'

## Expected output

2^26 passed
2^27 passed
2^28 passed

## Configuration
CPU: Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz
Memory: 1TB 
disk: network storage with quota of more than 1TB left

Platform:
- Linux

Installation method:
- Compiled from source
- glotzerlab-software container

Versions:
- Python version: 3.5.2
- **GSD** version: 1.81

**Comment by InnocentBug** [comment]
I know this is a really large file, but it would be great to write it in any case.
1 thought on this. If I do not add something to the particle positions, the script does not fail.

**Comment by InnocentBug** [comment]
Maybe I found a hint pointing to the problem.
In the source file gsd.c the function pwrite uses _write() to write to disk.
The comment next to it, suggests that this does not work for writes of more than 4GB.
Propably I am breaching this limit.

**Comment by InnocentBug** [comment]
I am no expert in HPC file IO, is there a way to circumvent this limit. Or could GSD split very large writes into smaller ones?

**Comment by InnocentBug** [comment]
Hmm, the comment in the code is only in a section which is defined for _WIN32 .
I'm on Linux.
